'use client';
import { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';

const LanguageContext = createContext(null);

const translations = {
  en: {
    dashboard: 'Dashboard',
    assets: 'Assets',
    locations: 'Locations',
    users: 'Users',
    onboarding: 'Onboarding',
    rolesPermissions: 'Roles & Permissions',
    auditLogs: 'Audit Logs',
    reports: 'Reports',
    logout: 'Logout',
    profile: 'Profile',
    license: 'License',
    tickets: 'Tickets',
    welcomeBack: 'Welcome back',
    systemOverview: "Here's your system overview",
    liveOverview: 'Live Overview',
    totalAssets: 'Total Assets',
    activeAssets: 'Active Assets',
    assigned: 'Assigned',
    needAttention: 'Need Attention',
    assetsStatus: 'Assets by Status',
    usersOnboarding: 'Users & Onboarding',
    recentActivity: 'Recent Activity Logs',
    searchPlaceholder: 'Search assets, users, logs...',
    loadingAnalytics: 'Loading dashboard analytics...',
    noAssetData: 'No asset distribution data available',
    noActivityLogs: 'No activity logs recorded yet',
    activeUsers: 'Active Users',
    pending: 'Pending',
    language: 'Language',
    brand: 'Brand',
    category: 'Category',
    location: 'Location',
    allocatedTo: 'Allocated To',
    unassigned: 'Unassigned',
    view: 'View',
    edit: 'Edit',
    allocate: 'Allocate',
    return: 'Return',
    delete: 'Delete',
    requestedAsset: 'Requested Asset',
    requestedBy: 'Requested By',
    status: 'Status',
    remarks: 'Remarks',
    actions: 'Actions',
    markPurchased: 'Mark Purchased',
    addAndAllocate: 'Add & Allocate',
    noActionRequired: 'No action required',
    id: 'ID',
    employee: 'Employee',
    suggestedCorporateEmail: 'Suggested Corporate Email',
    onboardingStatus: 'Onboarding Status',
    emailStatus: 'Email Status',
    itActions: 'IT Actions',
    permissionScopeName: 'Permission Scope Name',
    description: 'Description',
    assetTag: 'Asset Tag',
    assetDetails: 'Asset Details',
    assignedTo: 'Assigned To',
    assignedEmployee: 'Assigned Employee',
    allocatedBy: 'Allocated By',
    notesReason: 'Notes / Reason',
    state: 'State',
    allocatedDate: 'Allocated Date',
    returnedDate: 'Returned Date',
    timestamp: 'Timestamp',
    performedBy: 'Performed By',
    logDetails: 'Log Details',
    previous: 'Previous',
    next: 'Next',
    addRole: 'Add Role',
    addPermission: 'Add Permission',
    refresh: 'Refresh',
    roles: 'Roles',
    permissions: 'Permissions',
    saveChanges: 'Save Changes',
    systemPermissionsConfiguration: 'System Permissions Configuration',
    searchPermissionsPlaceholder: 'Search permissions by scope name or description...',
    roleName: 'Role Name',
    permissionName: 'Permission Scope Name',
    cancel: 'Cancel',
    save: 'Save',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    critical: 'Critical',
    available: 'Available',
    allocated: 'Allocated',
    inUse: 'In Use',
    underRepair: 'Under Repair',
    maintenance: 'Maintenance',
    retired: 'Retired',
    completed: 'Completed',
    draft: 'Draft',
    pending_approval: 'Pending Approval',
    approved: 'Approved',
    rejected: 'Rejected',
    active: 'Active',
    returned: 'Returned',
    laptop: 'Laptop',
    desktop: 'Desktop',
    mobile: 'Mobile',
    monitor: 'Monitor',
    accessories: 'Accessories',
    other: 'Other',
    superAdmin: 'Super Admin',
    admin: 'Admin',
    locationAdmin: 'Location Admin',
    itAdmin: 'IT Admin',
    user: 'User',
    subject: 'Subject',
    priority: 'Priority',
    raisedBy: 'Raised By',
    assignee: 'Assignee',
    lastUpdated: 'Last Updated',
    ticketId: 'Ticket ID',
    software: 'Software',
    licenseKey: 'License Key',
    totalSeats: 'Total Seats',
    seatsUsed: 'Seats Used',
    purchasedDate: 'Purchased Date',
    supportTickets: 'Support Tickets',
    recentSupportTickets: 'Recent Support Tickets',
    recentAssetRequests: 'Recent Asset Requests',
    recentSoftwareLicenses: 'Recent Software Licenses',
    recentRenewalRequests: 'Recent Renewal Requests',
    comparativeTrends: 'Comparative Trends',
    requestLifecycleStatistics: 'Request & Lifecycle Statistics',
    viewAll: 'View All',
    noRecentTickets: 'No recent tickets',
    noRecentAssetRequests: 'No recent asset requests',
    noRecentSoftwareLicenses: 'No recent software licenses',
    noRecentRenewalRequests: 'No recent renewal requests',
    decided: 'Decided',
    closed: 'Closed',
    resolved: 'Resolved',
    assignDirectlyToRoles: 'Assign directly to Roles',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    assets: 'संपत्तियां',
    locations: 'स्थान',
    users: 'उपयोगकर्ता',
    onboarding: 'ऑनबोर्डिंग',
    rolesPermissions: 'भूमिकाएं और अनुमतियां',
    auditLogs: 'ऑडिट लॉग्स',
    reports: 'रिपोर्ट्स',
    logout: 'लॉगआउट',
    profile: 'प्रोफाइल',
    license: 'लाइसेंस',
    tickets: 'टिकट',
    welcomeBack: 'वापसी पर आपका स्वागत है',
    systemOverview: 'यहाँ आपका सिस्टम अवलोकन है',
    liveOverview: 'लाइव अवलोकन',
    totalAssets: 'कुल संपत्तियां',
    activeAssets: 'सक्रिय संपत्तियां',
    assigned: 'आवंटित',
    needAttention: 'ध्यान देने की आवश्यकता',
    assetsStatus: 'स्थिति के अनुसार संपत्तियां',
    usersOnboarding: 'उपयोगकर्ता और ऑनबोर्डिंग',
    recentActivity: 'हालिया गतिविधि लॉग',
    searchPlaceholder: 'संपत्तियां, उपयोगकर्ता, लॉग खोजें...',
    loadingAnalytics: 'डैशबोर्ड विश्लेषण लोड हो रहा है...',
    noAssetData: 'कोई संपत्ति वितरण डेटा उपलब्ध नहीं है',
    noActivityLogs: 'अभी तक कोई गतिविधि लॉग दर्ज नहीं की गई है',
    activeUsers: 'सक्रिय उपयोगकर्ता',
    pending: 'लंबित',
    language: 'भाषा',
    brand: 'ब्रांड',
    category: 'श्रेणी',
    location: 'स्थान',
    allocatedTo: 'को आवंटित',
    unassigned: 'अनअसाइन किया गया',
    view: 'देखें',
    edit: 'संपादित करें',
    allocate: 'आवंटित करें',
    return: 'वापस करें',
    delete: 'हटाएं',
    requestedAsset: 'अनुरोधित संपत्ति',
    requestedBy: 'अनुरोधक',
    status: 'स्थिति',
    remarks: 'टिप्पणी',
    actions: 'कार्रवाई',
    markPurchased: 'खरीदा गया चिह्नित करें',
    addAndAllocate: 'जोड़ें और आवंटित करें',
    noActionRequired: 'किसी कार्रवाई की आवश्यकता नहीं',
    id: 'आईडी',
    employee: 'कर्मचारी',
    suggestedCorporateEmail: 'सुझाया गया कॉर्पोरेट ईमेल',
    onboardingStatus: 'ऑनबोर्डिंग स्थिति',
    emailStatus: 'ईमेल स्थिति',
    itActions: 'आईटी कार्रवाई',
    permissionScopeName: 'अनुमति क्षेत्र नाम',
    description: 'विवरण',
    assetTag: 'संपत्ति टैग',
    assetDetails: 'संपत्ति विवरण',
    assignedTo: 'को सौंपा गया',
    assignedEmployee: 'सौंपा गया कर्मचारी',
    allocatedBy: 'द्वारा आवंटित',
    notesReason: 'नोट्स / कारण',
    state: 'राज्य',
    allocatedDate: 'आवंटित तिथि',
    returnedDate: 'लौटाए जाने की तिथि',
    timestamp: 'समय',
    performedBy: 'द्वारा किया गया',
    logDetails: 'लॉग विवरण',
    previous: 'पिछला',
    next: 'अगला',
    addRole: 'भूमिका जोड़ें',
    addPermission: 'अनुमति जोड़ें',
    refresh: 'रीफ्रेश',
    roles: 'भूमिकाएं',
    permissions: 'अनुमतियां',
    saveChanges: 'परिवर्तनों को सहेजें',
    systemPermissionsConfiguration: 'सिस्टम अनुमतियां कॉन्फ़िगरेशन',
    searchPermissionsPlaceholder: 'स्कोप नाम या विवरण द्वारा अनुमतियाँ खोजें...',
    roleName: 'भूमिका का नाम',
    permissionName: 'अनुमति क्षेत्र नाम',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    critical: 'गंभीर',
    available: 'उपलब्ध',
    allocated: 'आवंटित',
    inUse: 'उपयोग में',
    underRepair: 'मरम्मत के अधीन',
    maintenance: 'रखरखाव',
    retired: 'सेवानिवृत्त',
    completed: 'पूरा हुआ',
    draft: 'ड्राफ्ट',
    pending_approval: 'अनुमोदन लंबित',
    approved: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    active: 'सक्रिय',
    returned: 'लौटा दिया गया',
    laptop: 'लैपटॉप',
    desktop: 'डेस्कटॉप',
    mobile: 'मोबाइल',
    monitor: 'मॉनिटर',
    accessories: 'सामान',
    other: 'अन्य',
    superAdmin: 'सुपर एडमिन',
    admin: 'एडमिन',
    locationAdmin: 'स्थान एडमिन',
    itAdmin: 'आईटी एडमिन',
    user: 'उपयोगकर्ता',
    subject: 'विषय',
    priority: 'प्राथमिकता',
    raisedBy: 'द्वारा उठाया गया',
    assignee: 'सौंपा गया',
    lastUpdated: 'अंतिम अपडेट',
    ticketId: 'टिकट आईडी',
    software: 'सॉफ्टवेयर',
    licenseKey: 'लाइसेंस कुंजी',
    totalSeats: 'कुल सीटें',
    seatsUsed: 'उपयोग की गई सीटें',
    validUntil: 'तक मान्य',
    purchasedDate: 'खरीद की तारीख',
    assignDirectlyToRoles: 'भूमिकाओं को सीधे सौंपें',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    assets: 'சொத்துக்கள்',
    locations: 'இடங்கள்',
    users: 'பயனர்கள்',
    onboarding: 'ஆன்போர்டிங்',
    rolesPermissions: 'பணிகள் & அனுமதிகள்',
    auditLogs: 'தணிக்கை பதிவுகள்',
    reports: 'அறிக்கைகள்',
    logout: 'வெளியேறு',
    profile: 'சுயவிவரம்',
    license: 'உரிமம்',
    tickets: 'டிக்கெட்டுகள்',
    welcomeBack: 'மீண்டும் வருக',
    systemOverview: 'உங்கள் கணினி மேலோட்டம் இதோ',
    liveOverview: 'நேரடி மேலோட்டம்',
    totalAssets: 'மொத்த சொத்துக்கள்',
    activeAssets: 'செயலில் உள்ள சொத்துக்கள்',
    assigned: 'ஒதுக்கப்பட்டவை',
    needAttention: 'கமனிப்பு தேவைப்படுபவை',
    assetsStatus: 'நிலையின்படி சொத்துக்கள்',
    usersOnboarding: 'பயனர்கள் & ஆன்போர்டிங்',
    recentActivity: 'சமீபத்திய செயல்பாட்டு பதிவுகள்',
    searchPlaceholder: 'சொத்துக்கள், பயனர்கள், பதிவுகளைத் தேடுங்கள்...',
    loadingAnalytics: 'டாஷ்போர்டு பகுப்பாய்வு ஏற்றப்படுகிறது...',
    noAssetData: 'சொத்து விநியோக தரவு இல்லை',
    noActivityLogs: 'செயல்பாட்டு பதிவுகள் எதுவும் இல்லை',
    activeUsers: 'செயலில் உள்ள பயனர்கள்',
    pending: 'நிலுவையில் உள்ளது',
    language: 'மொழி',
    brand: 'பிராண்ட்',
    category: 'வகை',
    location: 'இடம்',
    allocatedTo: 'ஒதுக்கப்பட்டது',
    unassigned: 'ஒதுக்கப்படாதது',
    view: 'பார்வை',
    edit: 'திருத்து',
    allocate: 'ஒதுக்கு',
    return: 'திருப்பு',
    delete: 'அழி',
    requestedAsset: 'கோரப்பட்ட சொத்து',
    requestedBy: 'கோரியவர்',
    status: 'நிலை',
    remarks: 'குறிப்புகள்',
    actions: 'செயல்கள்',
    markPurchased: 'வாங்கப்பட்டது என குறிக்கவும்',
    addAndAllocate: 'சேர்த்து ஒதுக்குக',
    noActionRequired: 'செயல்பாடு தேவையில்லை',
    id: 'ஐடி',
    employee: 'பணியாளர்',
    suggestedCorporateEmail: 'பரிந்துரைக்கப்பட்ட கார்ப்பரேட் மின்னஞ்சல்',
    onboardingStatus: 'ஆன்போர்டிங் நிலை',
    emailStatus: 'மின்னஞ்சல் நிலை',
    itActions: 'ஐடி செயல்கள்',
    permissionScopeName: 'அனுமதி வரம்பு பெயர்',
    description: 'விளக்கம்',
    assetTag: 'சொத்து குறிச்சொல்',
    assetDetails: 'சொத்து विवरणங்கள்',
    assignedTo: 'ஒப்படைக்கப்பட்டது',
    assignedEmployee: 'ஒப்படைக்கப்பட்ட பணியாளர்',
    allocatedBy: 'ஒதுக்கியவர்',
    notesReason: 'குறிப்புகள் / காரணம்',
    state: 'மாநிலம்',
    allocatedDate: 'ஒதுக்கப்பட்ட தேதி',
    returnedDate: 'திருப்பி அனுப்பப்பட்ட தேதி',
    timestamp: 'நேரம்',
    performedBy: 'செய்தவர்',
    logDetails: 'பதிவு விவரங்கள்',
    previous: 'முந்தைய',
    next: 'அடுத்தது',
    addRole: 'பணியைச் சேர்',
    addPermission: 'அனுமதியைச் சேர்',
    refresh: 'புதுப்பி',
    roles: 'பணிகள்',
    permissions: 'அனுமதிகள்',
    saveChanges: 'மாற்றங்களைச் சேமி',
    systemPermissionsConfiguration: 'கணினி அனுமதிகள் கட்டமைப்பு',
    searchPermissionsPlaceholder: 'அனுமதி பெயர் அல்லது விளக்கத்தின் மூலம் தேடவும்...',
    roleName: 'பணியின் பெயர்',
    permissionName: 'அனுமதி வரம்பு பெயர்',
    cancel: 'ரத்து செய்',
    save: 'சேமி',
    low: 'குறைந்த',
    medium: 'நடுத்தர',
    high: 'அதிக',
    critical: 'முக்கியமான',
    available: 'கிடைக்கக்கூடியது',
    allocated: 'ஒதுக்கப்பட்டது',
    inUse: 'பயன்பாட்டில் உள்ளது',
    underRepair: 'பழுதுபார்ப்பில் உள்ளது',
    maintenance: 'பராமரிப்பு',
    retired: 'ஓய்வு பெற்றது',
    completed: 'முடிந்தது',
    draft: 'வரைவு',
    pending_approval: 'அனுமதி நிலுவையில் உள்ளது',
    approved: 'அங்கீகரிக்கப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    active: 'செயலில்',
    returned: 'திருப்பப்பட்டது',
    laptop: 'லேப்டாப்',
    desktop: 'டெஸ்க்டாப்',
    mobile: 'மொபைல்',
    monitor: 'மானிட்டர்',
    accessories: 'துணைக்கருவிகள்',
    other: 'மற்றவை',
    superAdmin: 'சூப்பர் அட்மின்',
    admin: 'அட்மின்',
    locationAdmin: 'இட அட்மின்',
    itAdmin: 'ஐடி அட்மின்',
    user: 'பயனர்',
    subject: 'பொருள்',
    priority: 'முன்னுரிமை',
    raisedBy: 'எழுப்பியவர்',
    assignee: 'ஒதுக்கப்பட்டவர்',
    lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    ticketId: 'டிக்கெட் ஐடி',
    software: 'மென்பொருள்',
    licenseKey: 'உரிம விசை',
    totalSeats: 'மொத்த இருக்கைகள்',
    seatsUsed: 'பயன்படுத்தப்பட்ட இருக்கைகள்',
    validUntil: 'வரை செல்லுபடியாகும்',
    purchasedDate: 'வாங்கப்பட்ட தேதி',
    assignDirectlyToRoles: 'பணிகளுக்கு நேரடியாக ஒதுக்குங்கள்',
  },
  ms: {
    dashboard: 'Papan Pemuka',
    assets: 'Aset',
    locations: 'Lokasi',
    users: 'Pengguna',
    onboarding: 'Kemasukan',
    rolesPermissions: 'Peranan & Kebenaran',
    auditLogs: 'Log Audit',
    reports: 'Laporan',
    logout: 'Log Keluar',
    profile: 'Profil',
    license: 'Lesen',
    tickets: 'Tiket',
    welcomeBack: 'Selamat kembali',
    systemOverview: 'Ini adalah gambaran keseluruhan sistem anda',
    liveOverview: 'Gambaran Keseluruhan Langsung',
    totalAssets: 'Jumlah Aset',
    activeAssets: 'Aset Aktif',
    assigned: 'Diperuntukkan',
    needAttention: 'Perlu Perhatian',
    assetsStatus: 'Aset mengikut Status',
    usersOnboarding: 'Pengguna & Kemasukan',
    recentActivity: 'Log Aktiviti Terkini',
    searchPlaceholder: 'Cari aset, pengguna, log...',
    loadingAnalytics: 'Memuatkan analisis papan pemuka...',
    noAssetData: 'Tiada data pengedaran aset tersedia',
    noActivityLogs: 'Tiada log aktiviti direkodkan lagi',
    activeUsers: 'Pengguna Aktif',
    pending: 'Belum Selesai',
    language: 'Bahasa',
    brand: 'Jenama',
    category: 'Kategori',
    location: 'Lokasi',
    allocatedTo: 'Diserahkan Kepada',
    unassigned: 'Tidak Diserahkan',
    view: 'Lihat',
    edit: 'Edit',
    allocate: 'Serah',
    return: 'Pulang',
    delete: 'Padam',
    requestedAsset: 'Aset Diminta',
    requestedBy: 'Diminta Oleh',
    status: 'Status',
    remarks: 'Nota',
    actions: 'Tindakan',
    markPurchased: 'Tandakan Dibeli',
    addAndAllocate: 'Tambah & Serah',
    noActionRequired: 'Tiada tindakan diperlukan',
    id: 'ID',
    employee: 'Pekerja',
    suggestedCorporateEmail: 'Cadangan Emel Korporat',
    onboardingStatus: 'Status Kemasukan',
    emailStatus: 'Status Emel',
    itActions: 'Tindakan IT',
    permissionScopeName: 'Nama Skop Kebenaran',
    description: 'Keterangan',
    assetTag: 'Tag Aset',
    assetDetails: 'Butiran Aset',
    assignedTo: 'Ditugaskan Kepada',
    assignedEmployee: 'Pekerja Ditugaskan',
    allocatedBy: 'Diserahkan Oleh',
    notesReason: 'Nota / Sebab',
    state: 'Negeri',
    allocatedDate: 'Tarikh Serah',
    returnedDate: 'Tarikh Pulang',
    timestamp: 'Masa',
    performedBy: 'Dilakukan Oleh',
    logDetails: 'Butiran Log',
    previous: 'Sebelumnya',
    next: 'Seterusnya',
    addRole: 'Tambah Peranan',
    addPermission: 'Tambah Kebenaran',
    refresh: 'Segar Semula',
    roles: 'Peranan',
    permissions: 'Kebenaran',
    saveChanges: 'Simpan Perubahan',
    systemPermissionsConfiguration: 'Konfigurasi Kebenaran Sistem',
    searchPermissionsPlaceholder: 'Cari kebenaran mengikut nama skop atau keterangan...',
    roleName: 'Nama Peranan',
    permissionName: 'Nama Skop Kebenaran',
    cancel: 'Batal',
    save: 'Simpan',
    low: 'Rendah',
    medium: 'Sederhana',
    high: 'Tinggi',
    critical: 'Kritikal',
    available: 'Tersedia',
    allocated: 'Diserahkan',
    inUse: 'Sedang Digunakan',
    underRepair: 'Dalam Pembaikan',
    maintenance: 'Penyelenggaraan',
    retired: 'Bersara',
    completed: 'Selesai',
    draft: 'Draf',
    pending_approval: 'Menunggu Kelulusan',
    approved: 'Diluluskan',
    rejected: 'Ditolak',
    active: 'Aktif',
    returned: 'Dipulangkan',
    laptop: 'Komputer Riba',
    desktop: 'Komputer Meja',
    mobile: 'Telefon Bimbit',
    monitor: 'Monitor',
    accessories: 'Aksesori',
    other: 'Lain-lain',
    superAdmin: 'Super Admin',
    admin: 'Admin',
    locationAdmin: 'Admin Lokasi',
    itAdmin: 'Admin IT',
    user: 'Pengguna',
    subject: 'Subjek',
    priority: 'Keutamaan',
    raisedBy: 'Dikemukakan Oleh',
    assignee: 'Penerima Tugas',
    lastUpdated: 'Kemas Kini Terakhir',
    ticketId: 'ID Tiket',
    software: 'Perisian',
    licenseKey: 'Kunci Lesen',
    totalSeats: 'Jumlah Tempat',
    seatsUsed: 'Tempat Digunakan',
    validUntil: 'Sah Sehingga',
    purchasedDate: 'Tarikh Dibeli',
    assignDirectlyToRoles: 'Serahkan terus kepada Peranan',
  },
  sw: {
    dashboard: 'Tabuta ya Dashboard',
    assets: 'Mali',
    locations: 'Maeneo',
    users: 'Watumiaji',
    onboarding: 'Kuingiza',
    rolesPermissions: 'Majukumu na Ruhusa',
    auditLogs: 'Kumbukumbu za Ukaguzi',
    reports: 'Ripoti',
    logout: 'Ondoka',
    profile: 'Wasifu',
    license: 'Leseni',
    tickets: 'Tiketi',
    welcomeBack: 'Karibu tena',
    systemOverview: 'Huu hapa muhtasari wa mfumo wako',
    liveOverview: 'Muhtasari wa Moja kwa Moja',
    totalAssets: 'Jumla ya Mali',
    activeAssets: 'Mali Zinazotumika',
    assigned: 'Zilizogawiwa',
    needAttention: 'Inahitaji Uangalifu',
    assetsStatus: 'Mali kwa Hali',
    usersOnboarding: 'Watumiaji & Kuingiza',
    recentActivity: 'Kumbukumbu za Shughuli za Hivi Karibuni',
    searchPlaceholder: 'Tafuta mali, watumiaji, kumbukumbu...',
    loadingAnalytics: 'Inapakia uchanganuzi wa dashboard...',
    noAssetData: 'Hakuna data ya usambazaji wa mali inayopatikana',
    noActivityLogs: 'Hakuna kumbukumbu za shughuli zilizorekodiwa bado',
    activeUsers: 'Watumiaji Amilifu',
    pending: 'Inasubiri',
    language: 'Lugha',
    brand: 'Chapa',
    category: 'Kundi',
    location: 'Mahali',
    allocatedTo: 'Imekabidhiwa Kwa',
    unassigned: 'Haijagawiwa',
    view: 'Angalia',
    edit: 'Hariri',
    allocate: 'Kukabidhi',
    return: 'Rudisha',
    delete: 'Futa',
    requestedAsset: 'Mali Inayoombwa',
    requestedBy: 'Imeombwa Na',
    status: 'Hali',
    remarks: 'Maoni',
    actions: 'Vitendo',
    markPurchased: 'Weka Alama Imenunuliwa',
    addAndAllocate: 'Ongeza & Kabidhi',
    noActionRequired: 'Hakuna hatua inayohitajika',
    id: 'Kitambulisho',
    employee: 'Mfanyakazi',
    suggestedCorporateEmail: 'Barua Pepe Inayopendekezwa',
    onboardingStatus: 'Hali ya Kuingiza',
    emailStatus: 'Hali ya Barua Pepe',
    itActions: 'Vitendo vya IT',
    permissionScopeName: 'Jina la Upeo wa Ruhusa',
    description: 'Maelezo',
    assetTag: 'Lebo ya Mali',
    assetDetails: 'Maelezo ya Mali',
    assignedTo: 'Imekabidhiwa Kwa',
    assignedEmployee: 'Mfanyakazi Aliyekabidhiwa',
    allocatedBy: 'Imegawiwa Na',
    notesReason: 'Maelezo / Sababu',
    state: 'Jimbo',
    allocatedDate: 'Tarehe ya Kukabidhi',
    returnedDate: 'Tarehe ya Kurudisha',
    timestamp: 'Muda',
    performedBy: 'Imefanywa Na',
    logDetails: 'Maelezo ya Kumbukumbu',
    previous: 'Iliyotangulia',
    next: 'Inayofuata',
    addRole: 'Ongeza Jukumu',
    addPermission: 'Ongeza Ruhusa',
    refresh: 'Pakia upya',
    roles: 'Majukumu',
    permissions: 'Ruhusa',
    saveChanges: 'Hifadhi Mabadiliko',
    systemPermissionsConfiguration: 'Usanidi wa Ruhusa za Mfumo',
    searchPermissionsPlaceholder: 'Tafuta ruhusa kwa jina au maelezo...',
    roleName: 'Jina la Jukumu',
    permissionName: 'Jina la Upeo wa Ruhusa',
    cancel: 'Ghairi',
    save: 'Hifadhi',
    low: 'Chini',
    medium: 'Kati',
    high: 'Juu',
    critical: 'Muhimu Sana',
    available: 'Inapatikana',
    allocated: 'Imekabidhiwa',
    inUse: 'Inatumika',
    underRepair: 'Inarekebishwa',
    maintenance: 'Matengenezo',
    retired: 'Imestaafu',
    completed: 'Imekamilika',
    draft: 'Rasimu',
    pending_approval: 'Inasubiri Kuidhinishwa',
    approved: 'Imeidhinishwa',
    rejected: 'Imekataliwa',
    active: 'Amilifu',
    returned: 'Imerudishwa',
    laptop: 'Kompyuta mpakato',
    desktop: 'Kompyuta ya mezani',
    mobile: 'Simu ya mkononi',
    monitor: 'Monita',
    accessories: 'Vifaa vya ziada',
    other: 'Nyingine',
    superAdmin: 'Msimamizi Mkuu',
    admin: 'Msimamizi',
    locationAdmin: 'Msimamizi wa Mahali',
    itAdmin: 'Msimamizi wa IT',
    user: 'Mtumiaji',
    subject: 'Mada',
    priority: 'Kipaumbele',
    raisedBy: 'Imeanzishwa Na',
    assignee: 'Mteule',
    lastUpdated: 'Ilisasishwa Mwisho',
    ticketId: 'Kitambulisho cha Tiketi',
    software: 'Programu',
    licenseKey: 'Ufunguo wa Leseni',
    totalSeats: 'Jumla ya Viti',
    seatsUsed: 'Viti Vilivyotumika',
    validUntil: 'Inafaa Hadi',
    purchasedDate: 'Tarehe ya Kununua',
    assignDirectlyToRoles: 'Kukabidhi moja kwa moja kwa Majukumu',
  },
  ar: {
    dashboard: 'لوحة القيادة',
    assets: 'الأصول',
    locations: 'المواقع',
    users: 'المستخدمين',
    onboarding: 'التهيئة والتدريب',
    rolesPermissions: 'الأدوار والأذونات',
    auditLogs: 'سجلات التدقيق',
    reports: 'التقارير',
    logout: 'تسجيل الخروج',
    profile: 'الملف الشخصي',
    license: 'الترخيص',
    tickets: 'التذاكر',
    welcomeBack: 'مرحباً بك مجدداً',
    systemOverview: 'إليك نظرة عامة على النظام الخاص بك',
    liveOverview: 'نظرة عامة مباشرة',
    totalAssets: 'إجمالي الأصول',
    activeAssets: 'الأصول النشطة',
    assigned: 'مخصص',
    needAttention: 'بحاجة إلى اهتمام',
    assetsStatus: 'الأصول حسب الحالة',
    usersOnboarding: 'المستخدمين والتهيئة',
    recentActivity: 'سجلات النشاط الأخيرة',
    searchPlaceholder: 'البحث عن الأصول، المستخدمين، السجلات...',
    loadingAnalytics: 'جاري تحميل تحليلات لوحة القيادة...',
    noAssetData: 'لا توجد بيانات متاحة لتوزيع الأصول',
    noActivityLogs: 'لم يتم تسجيل أي سجلات نشاط بعد',
    activeUsers: 'المستخدمين النشطين',
    pending: 'قيد الانتظار',
    language: 'اللغة',
    brand: 'العلامة التجارية',
    category: 'الفئة',
    location: 'الموقع',
    allocatedTo: 'مخصص لـ',
    unassigned: 'غير مخصص',
    view: 'عرض',
    edit: 'تعديل',
    allocate: 'تخصيص',
    return: 'إرجاع',
    delete: 'حذف',
    requestedAsset: 'الأصل المطلوب',
    requestedBy: 'مطلوب بواسطة',
    status: 'الحالة',
    remarks: 'ملاحظات',
    actions: 'الإجراءات',
    markPurchased: 'تحديد كمشتريات',
    addAndAllocate: 'إضافة وتخصيص',
    noActionRequired: 'لا يوجد إجراء مطلوب',
    id: 'المعرف',
    employee: 'الموظف',
    suggestedCorporateEmail: 'البريد الإلكتروني المقترح للشركة',
    onboardingStatus: 'حالة التهيئة',
    emailStatus: 'حالة البريد الإلكتروني',
    itActions: 'إجراءات تكنولوجيا المعلومات',
    permissionScopeName: 'اسم نطاق الصلاحية',
    description: 'الوصف',
    assetTag: 'علامة الأصل',
    assetDetails: 'تفاصيل الأصل',
    assignedTo: 'مسند إلى',
    assignedEmployee: 'الموظف المسند إليه',
    allocatedBy: 'تم التخصيص بواسطة',
    notesReason: 'ملاحظات / السبب',
    state: 'الولاية / المنطقة',
    allocatedDate: 'تاريخ التخصيص',
    returnedDate: 'تاريخ الإرجاع',
    timestamp: 'طابع زمني',
    performedBy: 'تم بواسطة',
    logDetails: 'تفاصيل السجل',
    previous: 'السابق',
    next: 'التالي',
    addRole: 'إضافة دور',
    addPermission: 'إضافة صلاحية',
    refresh: 'تحديث',
    roles: 'الأدوار',
    permissions: 'الصلاحيات',
    saveChanges: 'حفظ التغييرات',
    systemPermissionsConfiguration: 'تكوين صلاحيات النظام',
    searchPermissionsPlaceholder: 'البحث عن الصلاحيات حسب الاسم أو الوصف...',
    roleName: 'اسم الدور',
    permissionName: 'اسم نطاق الصلاحية',
    cancel: 'إلغاء',
    save: 'حفظ',
    low: 'منخفض',
    medium: 'متوسط',
    high: 'مرتفع',
    critical: 'حرج',
    available: 'متاح',
    allocated: 'مخصص',
    inUse: 'قيد الاستخدام',
    underRepair: 'قيد الإصلاح',
    maintenance: 'صيانة',
    retired: 'خارج الخدمة',
    completed: 'مكتمل',
    draft: 'مسودة',
    pending_approval: 'في انتظار الموافقة',
    approved: 'مقبول',
    rejected: 'مرفوض',
    active: 'نشط',
    returned: 'تم إرجاعه',
    laptop: 'حاسوب محمول',
    desktop: 'حاسوب مكتبي',
    mobile: 'هاتف محمول',
    monitor: 'شاشة',
    accessories: 'ملحقات',
    other: 'أخرى',
    superAdmin: 'مسؤول فائق',
    admin: 'مسؤول',
    locationAdmin: 'مسؤول الموقع',
    itAdmin: 'مسؤول تكنولوجيا المعلومات',
    user: 'مستخدم',
    subject: 'الموضوع',
    priority: 'الأولوية',
    raisedBy: 'تم رفعه بواسطة',
    assignee: 'المعين',
    lastUpdated: 'آخر تحديث',
    ticketId: 'معرف التذكرة',
    software: 'البرمجيات',
    licenseKey: 'مفتاح الترخيص',
    totalSeats: 'إجمالي المقاعد',
    seatsUsed: 'المقاعد المستخدمة',
    validUntil: 'صالح حتى',
    purchasedDate: 'تاريخ الشراء',
    assignDirectlyToRoles: 'التعيين مباشرة للأدوار',
  }
};

const mapLocationToLang = (locationName) => {
  if (!locationName) return null;
  const name = locationName.toLowerCase().trim();
  if (name.includes('chennai')) return 'ta';
  if (name.includes('mumbai')) return 'hi';
  if (name.includes('difc') || name.includes('dubai') || name.includes('uae')) return 'ar';
  if (name.includes('kenya')) return 'sw';
  if (name.includes('malaysia')) return 'ms';
  if (name.includes('london') || name.includes('uk')) return 'en';
  return null;
};

const detectTimezoneLanguage = () => {
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (tz.includes('Kolkata')) return 'hi'; // Default India to Hindi as broad guess
    if (tz.includes('Kuala_Lumpur')) return 'ms';
    if (tz.includes('Nairobi')) return 'sw';
    if (tz.includes('Dubai') || tz.includes('Riyadh')) return 'ar';
    if (tz.includes('London') || tz.includes('Europe')) return 'en';
  } catch (e) {
    // ignore
  }
  return null;
};

const detectBrowserLanguage = () => {
  try {
    const lang = navigator.language || navigator.userLanguage;
    if (lang.startsWith('hi')) return 'hi';
    if (lang.startsWith('ta')) return 'ta';
    if (lang.startsWith('ms')) return 'ms';
    if (lang.startsWith('sw')) return 'sw';
    if (lang.startsWith('ar')) return 'ar';
    if (lang.startsWith('en')) return 'en';
  } catch (e) {
    // ignore
  }
  return null;
};

const detectIpLanguage = async () => {
  try {
    const res = await fetch('https://ipapi.co/json/');
    if (!res.ok) return null;
    const data = await res.json();
    const country = data.country_code;
    if (country === 'IN') return 'hi';
    if (country === 'MY') return 'ms';
    if (country === 'KE') return 'sw';
    if (country === 'AE') return 'ar';
    if (country === 'GB') return 'en';
  } catch (e) {
    // ignore
  }
  return null;
};

export function LanguageProvider({ children }) {
  const { user } = useAuth();
  const [language, setLanguage] = useState(() => {
    if (typeof window !== 'undefined') {
      const manualLang = localStorage.getItem('assetiq_lang');
      if (manualLang) return manualLang;
    }
    return 'en';
  });

  useEffect(() => {
    const manualLang = localStorage.getItem('assetiq_lang');
    if (!manualLang && user) {
      const locLang = mapLocationToLang(user.location) || detectTimezoneLanguage() || detectBrowserLanguage();
      if (locLang) {
        setTimeout(() => {
          setLanguage(prev => (prev !== locLang ? locLang : prev));
        }, 0);
      } else {
        detectIpLanguage().then(ipLang => {
          if (ipLang) {
            setTimeout(() => {
              setLanguage(prev => (prev !== ipLang ? ipLang : prev));
            }, 0);
          }
        });
      }
    } else if (!manualLang && !user) {
      setTimeout(() => {
        setLanguage(prev => (prev !== 'en' ? 'en' : prev));
      }, 0);
    }
  }, [user]);


  const changeLanguage = (langCode) => {
    setLanguage(langCode);
    localStorage.setItem('assetiq_lang', langCode);
  };

  const t = (key) => {
    if (!key) return '';
    const clean = String(key).trim();
    // Generate potential lookup keys
    const camelKey = clean.toLowerCase().replace(/[-_\s]+(.)?/g, (_, c) => c ? c.toUpperCase() : '');
    const lowerKey = clean.toLowerCase().replace(/_/g, ' ');
    
    const lang = translations[language] || {};
    const en = translations['en'] || {};
    
    // 1. Try language translation
    if (lang[key] !== undefined) return lang[key];
    if (lang[camelKey] !== undefined) return lang[camelKey];
    if (lang[lowerKey] !== undefined) return lang[lowerKey];
    
    // 2. Try English translation
    if (en[key] !== undefined) return en[key];
    if (en[camelKey] !== undefined) return en[camelKey];
    if (en[lowerKey] !== undefined) return en[lowerKey];
    
    // 3. Fallback: Format for display
    return clean.charAt(0).toUpperCase() + clean.slice(1);
  };

  const value = {
    language,
    changeLanguage,
    t
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
